# Generated by Django 6.0 on 2026-03-11 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_tier_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analysisusage',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='accounts.guestidentity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_hand_analyses_per_day_override',
            field=models.IntegerField(blank=True, help_text='Override daily hand limit for this user', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_session_analyses_per_day_override',
            field=models.IntegerField(blank=True, help_text='Override daily session limit for this user', null=True),
        ),
        migrations.AlterField(
            model_name='analysisusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='analysisusage',
            unique_together={('user', 'date', 'guest')},
        ),
    ]
