# Generated by Django 6.0 on 2026-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_analysisusage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_hand_analyses_balance',
            field=models.IntegerField(default=0, help_text='One-time top-up balance for hand analyses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra_session_analyses_balance',
            field=models.IntegerField(default=0, help_text='One-time top-up balance for session analyses'),
        ),
    ]
