# Generated by Django 6.0 on 2026-01-16 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WdicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-friendly session name (optional).",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("gg", "GGPoker"),
                            ("pokerstars", "PokerStars"),
                            ("888", "888poker"),
                        ],
                        default="unknown",
                        help_text="Poker platform / site.",
                        max_length=32,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Derived from earliest hand time if available.",
                        null=True,
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Derived from latest hand time if available.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wdic_sessions",
                        to="accounts.guestidentity",
                    ),
                ),
            ],
            options={
                "db_table": "wdic_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WdicHand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("gg", "GGPoker"),
                            ("pokerstars", "PokerStars"),
                            ("888", "888poker"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "hand_no",
                    models.CharField(
                        blank=True,
                        help_text="Hand identifier from poker site if available.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hand start time parsed from history if available.",
                        null=True,
                    ),
                ),
                ("raw_text", models.TextField()),
                (
                    "raw_hash",
                    models.CharField(
                        help_text="sha256(raw_text) used for deduplication per guest.",
                        max_length=64,
                    ),
                ),
                (
                    "actions_json",
                    models.JSONField(
                        blank=True,
                        help_text="Parsed actions snapshot (parser-dependent).",
                        null=True,
                    ),
                ),
                (
                    "parsed_version",
                    models.CharField(
                        default="v0.1.0",
                        help_text="Parser version used to generate actions_json.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wdic_hands",
                        to="accounts.guestidentity",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hands",
                        to="wdic.wdicsession",
                    ),
                ),
            ],
            options={
                "db_table": "wdic_hands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wdicsession",
            index=models.Index(
                fields=["guest", "-created_at"], name="wdic_sess_guest_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wdichand",
            index=models.Index(
                fields=["guest", "-created_at"], name="wdic_hand_guest_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wdichand",
            index=models.Index(
                fields=["session", "-created_at"], name="wdic_hand_sess_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wdichand",
            index=models.Index(
                fields=["guest", "hand_no"], name="wdic_hand_guest_handno_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wdichand",
            index=models.Index(
                fields=["guest", "started_at"], name="wdic_hand_guest_started_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wdichand",
            constraint=models.UniqueConstraint(
                fields=("guest", "raw_hash"), name="wdic_hand_unique_per_guest"
            ),
        ),
    ]
