# Generated by Django 6.0 on 2026-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wdic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wdichand",
            name="button_seat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="hero_cards_str",
            field=models.CharField(
                blank=True, help_text="Ah Kh", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="hero_collected",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="hero_position",
            field=models.CharField(
                blank=True, help_text="BTN, SB, BB, UTG, etc.", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="hero_seat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="max_players",
            field=models.IntegerField(
                default=6, help_text="Table size extracted from file (e.g. 6 or 9)"
            ),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="source",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("gg", "GGPoker"),
                    ("pokerstars", "PokerStars"),
                    ("n8", "Natural8"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="wdicsession",
            name="source",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("gg", "GGPoker"),
                    ("pokerstars", "PokerStars"),
                    ("n8", "Natural8"),
                ],
                default="unknown",
                help_text="Poker platform / site.",
                max_length=32,
            ),
        ),
    ]
