# Generated by Django 6.0 on 2026-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wdic", "0002_wdichand_button_seat_wdichand_hero_cards_str_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wdichand",
            name="hero_invested",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount hero put into the pot (bet + call + ante)",
                max_digits=20,
            ),
        ),
    ]
