# Generated by Django 6.0 on 2026-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wdic", "0003_wdichand_hero_invested"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="wdichand",
            name="wdic_hand_guest_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="wdichand",
            name="wdic_hand_sess_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="wdichand",
            name="wdic_hand_guest_handno_idx",
        ),
        migrations.RemoveIndex(
            model_name="wdichand",
            name="wdic_hand_guest_started_idx",
        ),
        migrations.RemoveIndex(
            model_name="wdicsession",
            name="wdic_sess_guest_created_idx",
        ),
        migrations.AddField(
            model_name="wdichand",
            name="flop_1",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="flop_2",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="flop_3",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="river",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="wdichand",
            name="turn",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="actions_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="hand_no",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="hero_cards_str",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="hero_invested",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total chips hero put in pot (bet+call+ante - returned)",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="hero_position",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="max_players",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="parsed_version",
            field=models.CharField(default="v0.4.0", max_length=32),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="raw_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="wdichand",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wdicsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wdicsession",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wdicsession",
            name="source",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("gg", "GGPoker"),
                    ("pokerstars", "PokerStars"),
                    ("n8", "Natural8"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="wdicsession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
