# Generated by Django 6.0 on 2026-03-09 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wdic", "0004_remove_wdichand_wdic_hand_guest_created_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WdicHandAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Markdown format analysis content"),
                ),
                (
                    "suggestion",
                    models.CharField(
                        blank=True,
                        help_text="Summary: e.g., FOLD_PREFLOP, GOOD_CALL",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("model_name", models.CharField(default="gpt-4o", max_length=64)),
                ("prompt_version", models.CharField(default="v1", max_length=32)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="wdic.wdichand",
                    ),
                ),
            ],
            options={
                "db_table": "wdic_hand_analysis",
            },
        ),
        migrations.CreateModel(
            name="WdicSessionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("model_name", models.CharField(default="gpt-4o", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="wdic.wdicsession",
                    ),
                ),
            ],
            options={
                "db_table": "wdic_session_analysis",
            },
        ),
    ]
