# Generated by Django 6.0 on 2026-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wdic", "0005_wdichandanalysis_wdicsessionanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="wdichandanalysis",
            name="key_mistakes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of technical errors identified",
            ),
        ),
        migrations.AddField(
            model_name="wdichandanalysis",
            name="score",
            field=models.IntegerField(
                default=0, help_text="Player's performance score (0-100)"
            ),
        ),
    ]
